CREATE TABLE assurance_case (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, subject_type text NOT NULL, subject_id text NOT NULL, status text NOT NULL DEFAULT 'open' CHECK(status IN('open','collecting','ready','assured','not_assured','archived')), opened_by uuid NOT NULL, opened_at timestamptz NOT NULL DEFAULT now(), closed_at timestamptz, UNIQUE(id,tenant_id));
CREATE TABLE responsibility_acceptance (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, case_id uuid NOT NULL, responsible_id uuid NOT NULL, work_ref text NOT NULL, commitment text NOT NULL, due_at timestamptz, service_expectation jsonb NOT NULL DEFAULT '{}', accepted_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), FOREIGN KEY(case_id,tenant_id) REFERENCES assurance_case(id,tenant_id));
CREATE TABLE verification_checkpoint (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, case_id uuid NOT NULL, name text NOT NULL, condition jsonb NOT NULL, independent_verification boolean NOT NULL DEFAULT false, due_at timestamptz, display_order integer NOT NULL, UNIQUE(id,tenant_id), UNIQUE(case_id,display_order), FOREIGN KEY(case_id,tenant_id) REFERENCES assurance_case(id,tenant_id));
CREATE TABLE completion_evidence (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, case_id uuid NOT NULL, checkpoint_id uuid NOT NULL, source_type text NOT NULL, source_id text NOT NULL, source_version text, checksum text, submitted_by uuid NOT NULL, submitted_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), FOREIGN KEY(case_id,tenant_id) REFERENCES assurance_case(id,tenant_id), FOREIGN KEY(checkpoint_id,tenant_id) REFERENCES verification_checkpoint(id,tenant_id));
CREATE TABLE checkpoint_result (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, checkpoint_id uuid NOT NULL, verifier_id uuid NOT NULL, result text NOT NULL CHECK(result IN('passed','failed','inconclusive')), rationale text NOT NULL, verified_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), FOREIGN KEY(checkpoint_id,tenant_id) REFERENCES verification_checkpoint(id,tenant_id));
CREATE TABLE execution_exception (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, case_id uuid NOT NULL, exception_type text NOT NULL, severity text NOT NULL, status text NOT NULL DEFAULT 'detected', owner_id uuid, detected_at timestamptz NOT NULL DEFAULT now(), resolution text, resolved_at timestamptz, UNIQUE(id,tenant_id), FOREIGN KEY(case_id,tenant_id) REFERENCES assurance_case(id,tenant_id));
CREATE TABLE recovery_request (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, exception_id uuid NOT NULL, target_system text NOT NULL, action text NOT NULL, idempotency_key text NOT NULL, status text NOT NULL DEFAULT 'requested', requested_by uuid NOT NULL, requested_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), UNIQUE(tenant_id,idempotency_key), FOREIGN KEY(exception_id,tenant_id) REFERENCES execution_exception(id,tenant_id));
CREATE TABLE reconciliation_run (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, case_id uuid NOT NULL, status text NOT NULL DEFAULT 'running', started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz, UNIQUE(id,tenant_id), FOREIGN KEY(case_id,tenant_id) REFERENCES assurance_case(id,tenant_id));
CREATE TABLE reconciliation_finding (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, run_id uuid NOT NULL, expected_state jsonb NOT NULL, observed_state jsonb NOT NULL, disposition text NOT NULL DEFAULT 'open', FOREIGN KEY(run_id,tenant_id) REFERENCES reconciliation_run(id,tenant_id));
CREATE TABLE reliability_observation (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, subject_type text NOT NULL, subject_id text NOT NULL, signal_type text NOT NULL, value numeric NOT NULL, evidence_ref text NOT NULL, observed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE trust_indicator (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, subject_type text NOT NULL, subject_id text NOT NULL, score numeric NOT NULL CHECK(score BETWEEN 0 AND 1), explanation jsonb NOT NULL, calculated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE assurance_briefing (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, case_id uuid, status text NOT NULL DEFAULT 'draft', content jsonb NOT NULL, issued_at timestamptz, UNIQUE(id,tenant_id), FOREIGN KEY(case_id,tenant_id) REFERENCES assurance_case(id,tenant_id));
CREATE TABLE assurance_advisory_request (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, case_id uuid, advisory_type text NOT NULL CHECK(advisory_type IN('nova','pops')), request_text text NOT NULL, response jsonb, status text NOT NULL DEFAULT 'requested', requested_by uuid NOT NULL, requested_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(case_id,tenant_id) REFERENCES assurance_case(id,tenant_id));
CREATE INDEX idx_case_status ON assurance_case(tenant_id,status);
CREATE INDEX idx_exception_open ON execution_exception(tenant_id,status,severity);
CREATE INDEX idx_reliability_subject ON reliability_observation(tenant_id,subject_type,subject_id,observed_at DESC);
CREATE OR REPLACE FUNCTION protect_assurance_records() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (TG_TABLE_NAME='assurance_case' AND OLD.status IN('assured','not_assured','archived')) THEN RAISE EXCEPTION 'closed assurance case is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_case_immutable BEFORE UPDATE OR DELETE ON assurance_case FOR EACH ROW EXECUTE FUNCTION protect_assurance_records();
CREATE OR REPLACE FUNCTION prevent_self_verification() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE owner_id uuid; independent boolean; BEGIN SELECT ra.responsible_id,vc.independent_verification INTO owner_id,independent FROM verification_checkpoint vc JOIN responsibility_acceptance ra ON ra.case_id=vc.case_id AND ra.tenant_id=vc.tenant_id WHERE vc.id=NEW.checkpoint_id AND vc.tenant_id=NEW.tenant_id; IF independent AND owner_id=NEW.verifier_id THEN RAISE EXCEPTION 'independent checkpoint cannot be self-verified'; END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_prevent_self_verification BEFORE INSERT ON checkpoint_result FOR EACH ROW EXECUTE FUNCTION prevent_self_verification();
CREATE OR REPLACE FUNCTION prevent_verified_evidence_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS(SELECT 1 FROM checkpoint_result r WHERE r.checkpoint_id=OLD.checkpoint_id AND r.tenant_id=OLD.tenant_id) THEN RAISE EXCEPTION 'verified evidence is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_evidence_immutable BEFORE UPDATE OR DELETE ON completion_evidence FOR EACH ROW EXECUTE FUNCTION prevent_verified_evidence_mutation();
ALTER TABLE assurance_case ENABLE ROW LEVEL SECURITY;
ALTER TABLE responsibility_acceptance ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_checkpoint ENABLE ROW LEVEL SECURITY;
ALTER TABLE completion_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkpoint_result ENABLE ROW LEVEL SECURITY;
ALTER TABLE execution_exception ENABLE ROW LEVEL SECURITY;
ALTER TABLE recovery_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE reconciliation_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE reconciliation_finding ENABLE ROW LEVEL SECURITY;
ALTER TABLE reliability_observation ENABLE ROW LEVEL SECURITY;
ALTER TABLE trust_indicator ENABLE ROW LEVEL SECURITY;
ALTER TABLE assurance_briefing ENABLE ROW LEVEL SECURITY;
ALTER TABLE assurance_advisory_request ENABLE ROW LEVEL SECURITY;
CREATE POLICY assurance_case_tenant ON assurance_case USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY responsibility_tenant ON responsibility_acceptance USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY checkpoint_tenant ON verification_checkpoint USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY evidence_tenant ON completion_evidence USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY checkpoint_result_tenant ON checkpoint_result USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY exception_tenant ON execution_exception USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY recovery_tenant ON recovery_request USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY reconciliation_tenant ON reconciliation_run USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY finding_tenant ON reconciliation_finding USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY reliability_tenant ON reliability_observation USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY trust_indicator_tenant ON trust_indicator USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY assurance_briefing_tenant ON assurance_briefing USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
CREATE POLICY assurance_advisory_tenant ON assurance_advisory_request USING(tenant_id=current_setting('app.tenant_id')::uuid) WITH CHECK(tenant_id=current_setting('app.tenant_id')::uuid);
