CREATE TABLE executive_workspace (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,tenant_id));
CREATE TABLE awareness_snapshot (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','acknowledged','archived')), observed_from timestamptz NOT NULL, observed_to timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,tenant_id), FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id));
CREATE TABLE health_indicator (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, snapshot_id uuid NOT NULL, metric_ref text NOT NULL, value jsonb NOT NULL, trend text, confidence numeric CHECK(confidence BETWEEN 0 AND 1), source_ref text NOT NULL, FOREIGN KEY(snapshot_id,tenant_id) REFERENCES awareness_snapshot(id,tenant_id));
CREATE TABLE organizational_pulse (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, snapshot_id uuid NOT NULL, summary text NOT NULL, material_changes jsonb NOT NULL DEFAULT '[]', UNIQUE(id,tenant_id), FOREIGN KEY(snapshot_id,tenant_id) REFERENCES awareness_snapshot(id,tenant_id));
CREATE TABLE strategic_briefing (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, title text NOT NULL, version integer NOT NULL DEFAULT 1, status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','ready','reviewed','issued','superseded','archived')), issued_at timestamptz, UNIQUE(id,tenant_id), UNIQUE(tenant_id,workspace_id,title,version), FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id));
CREATE TABLE briefing_section (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, briefing_id uuid NOT NULL, section_type text NOT NULL, display_order integer NOT NULL, content jsonb NOT NULL, citations jsonb NOT NULL DEFAULT '[]', UNIQUE(briefing_id,display_order), FOREIGN KEY(briefing_id,tenant_id) REFERENCES strategic_briefing(id,tenant_id));
CREATE TABLE executive_alert (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, alert_type text NOT NULL, severity text NOT NULL, status text NOT NULL DEFAULT 'raised', source_ref text NOT NULL, owner_id uuid, raised_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz, resolution_evidence jsonb, UNIQUE(id,tenant_id), FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id));
CREATE TABLE goal_reference (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, source_type text NOT NULL, source_id text NOT NULL, UNIQUE(id,tenant_id), UNIQUE(tenant_id,source_type,source_id), FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id));
CREATE TABLE initiative_observation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, goal_reference_id uuid, initiative_ref text NOT NULL, status text NOT NULL, progress numeric CHECK(progress BETWEEN 0 AND 1), observed_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id), FOREIGN KEY(goal_reference_id,tenant_id) REFERENCES goal_reference(id,tenant_id));
CREATE TABLE decision_readiness (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, subject_ref text NOT NULL, evidence_score numeric NOT NULL CHECK(evidence_score BETWEEN 0 AND 1), freshness_score numeric NOT NULL CHECK(freshness_score BETWEEN 0 AND 1), risk_coverage numeric NOT NULL CHECK(risk_coverage BETWEEN 0 AND 1), unresolved_conflicts integer NOT NULL DEFAULT 0, assessed_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id));
CREATE TABLE dependency_observation (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, snapshot_id uuid NOT NULL, upstream_ref text NOT NULL, downstream_ref text NOT NULL, status text NOT NULL, observed_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(snapshot_id,tenant_id) REFERENCES awareness_snapshot(id,tenant_id));
CREATE TABLE executive_timeline_entry (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, event_type text NOT NULL, subject_ref text NOT NULL, summary text NOT NULL, citations jsonb NOT NULL DEFAULT '[]', occurred_at timestamptz NOT NULL, FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id));
CREATE TABLE advisory_request (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL, workspace_id uuid NOT NULL, briefing_id uuid, advisory_type text NOT NULL CHECK(advisory_type IN('nova','pops')), request_text text NOT NULL, status text NOT NULL DEFAULT 'requested', response jsonb, requested_by uuid NOT NULL, requested_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(workspace_id,tenant_id) REFERENCES executive_workspace(id,tenant_id), FOREIGN KEY(briefing_id,tenant_id) REFERENCES strategic_briefing(id,tenant_id));
CREATE INDEX idx_snapshot_window ON awareness_snapshot(tenant_id,observed_to DESC);
CREATE INDEX idx_alert_open ON executive_alert(tenant_id,status,severity);
CREATE INDEX idx_timeline ON executive_timeline_entry(tenant_id,occurred_at DESC);
CREATE OR REPLACE FUNCTION protect_executive_records() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (TG_TABLE_NAME='strategic_briefing' AND OLD.status='issued') OR (TG_TABLE_NAME='awareness_snapshot' AND OLD.status='acknowledged') OR (TG_TABLE_NAME='executive_alert' AND OLD.status='closed') THEN RAISE EXCEPTION 'governed executive record is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER trg_briefing_immutable BEFORE UPDATE OR DELETE ON strategic_briefing FOR EACH ROW EXECUTE FUNCTION protect_executive_records();
CREATE TRIGGER trg_snapshot_immutable BEFORE UPDATE OR DELETE ON awareness_snapshot FOR EACH ROW EXECUTE FUNCTION protect_executive_records();
CREATE TRIGGER trg_alert_immutable BEFORE UPDATE OR DELETE ON executive_alert FOR EACH ROW EXECUTE FUNCTION protect_executive_records();
ALTER TABLE executive_workspace ENABLE ROW LEVEL SECURITY;
ALTER TABLE awareness_snapshot ENABLE ROW LEVEL SECURITY;
ALTER TABLE health_indicator ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizational_pulse ENABLE ROW LEVEL SECURITY;
ALTER TABLE strategic_briefing ENABLE ROW LEVEL SECURITY;
ALTER TABLE briefing_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE executive_alert ENABLE ROW LEVEL SECURITY;
ALTER TABLE goal_reference ENABLE ROW LEVEL SECURITY;
ALTER TABLE initiative_observation ENABLE ROW LEVEL SECURITY;
ALTER TABLE decision_readiness ENABLE ROW LEVEL SECURITY;
ALTER TABLE dependency_observation ENABLE ROW LEVEL SECURITY;
ALTER TABLE executive_timeline_entry ENABLE ROW LEVEL SECURITY;
ALTER TABLE advisory_request ENABLE ROW LEVEL SECURITY;
CREATE POLICY executive_workspace_tenant ON executive_workspace USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY awareness_snapshot_tenant ON awareness_snapshot USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY health_indicator_tenant ON health_indicator USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY organizational_pulse_tenant ON organizational_pulse USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY strategic_briefing_tenant ON strategic_briefing USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY briefing_section_tenant ON briefing_section USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY executive_alert_tenant ON executive_alert USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY goal_reference_tenant ON goal_reference USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY initiative_observation_tenant ON initiative_observation USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY decision_readiness_tenant ON decision_readiness USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY dependency_observation_tenant ON dependency_observation USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY executive_timeline_tenant ON executive_timeline_entry USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);
CREATE POLICY advisory_request_tenant ON advisory_request USING(tenant_id=(auth.jwt()->>'tenant_id')::uuid) WITH CHECK(tenant_id=(auth.jwt()->>'tenant_id')::uuid);

ALTER TABLE health_indicator ADD CONSTRAINT uq_health_indicator_id_tenant UNIQUE(id,tenant_id);
ALTER TABLE briefing_section ADD CONSTRAINT uq_briefing_section_id_tenant UNIQUE(id,tenant_id);
ALTER TABLE initiative_observation ADD CONSTRAINT uq_initiative_observation_id_tenant UNIQUE(id,tenant_id);
ALTER TABLE decision_readiness ADD CONSTRAINT uq_decision_readiness_id_tenant UNIQUE(id,tenant_id);
ALTER TABLE dependency_observation ADD CONSTRAINT uq_dependency_observation_id_tenant UNIQUE(id,tenant_id);
ALTER TABLE executive_timeline_entry ADD CONSTRAINT uq_executive_timeline_id_tenant UNIQUE(id,tenant_id);
ALTER TABLE advisory_request ADD CONSTRAINT uq_advisory_request_id_tenant UNIQUE(id,tenant_id);