import assert from "node:assert/strict";import test from "node:test";import {DispatchService} from "../src/dispatch/index.mjs";import {AuditLog,SecureAccess} from "../src/security/index.mjs";
const T="tenant-tngd",P="correct horse battery staple";
async function setup(){const auditLog=new AuditLog(),secureAccess=new SecureAccess({auditLog});await secureAccess.bootstrapTenantAdmin({tenantId:T,email:"owner@example.com",password:P});const owner=await secureAccess.authenticate({tenantId:T,email:"owner@example.com",password:P});
 const dispatcher=await secureAccess.createUser({actorSessionToken:owner.token,tenantId:T,email:"dispatch@example.com",password:P,roles:["admin_dispatch"]});const manager=await secureAccess.createUser({actorSessionToken:owner.token,tenantId:T,email:"manager@example.com",password:P,roles:["manager"]});const tech=await secureAccess.createUser({actorSessionToken:owner.token,tenantId:T,email:"tech@example.com",password:P,roles:["technician"]});
 const sessions={owner,dispatcher:await secureAccess.authenticate({tenantId:T,email:dispatcher.email,password:P}),manager:await secureAccess.authenticate({tenantId:T,email:manager.email,password:P}),tech:await secureAccess.authenticate({tenantId:T,email:tech.email,password:P})};
 const appointment=Object.freeze({id:"apt-1",tenantId:T,serviceCaseId:"case-1",customerId:"cust-1",status:"scheduled",startsAt:"2026-08-17T13:00:00Z",endsAt:"2026-08-17T14:00:00Z"});
 const schedulingService={getAuthorized:({appointmentId})=>appointmentId===appointment.id?appointment:null};const capacityService={calculateAuthorized:()=>Object.freeze({candidates:Object.freeze([{technicianId:tech.id,available:true,remainingCapacity:2,reasons:[]}])})};
 return{auditLog,secureAccess,sessions,tech,appointment,dispatch:new DispatchService({secureAccess,schedulingService,capacityService,auditLog})};}
const req=Object.freeze({serviceType:"repair",serviceArea:"raleigh",travelDistanceMiles:12,requiredSkills:["torsion-spring"],requiredEquipment:["ladder"],requiredVehicle:"service-van",emergency:false});
function item(c){return c.dispatch.createWorkItemAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,appointmentId:c.appointment.id,requirements:req});}
test("dispatcher queue creates one idempotent unassigned work item",async()=>{const c=await setup(),a=item(c),b=item(c);assert.equal(a,b);assert.equal(c.dispatch.listAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T}).length,1);});
test("capacity-aware recommendation explains eligible technicians",async()=>{const c=await setup(),w=item(c),r=c.dispatch.recommendAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id});assert.equal(r.candidates[0].technicianId,c.tech.id);assert.equal(r.status,"pending-human-approval");});
test("human approval separation prevents autonomous or self-approved assignment",async()=>{const c=await setup(),w=item(c),r=c.dispatch.recommendAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id});assert.throws(()=>c.dispatch.assignAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id,recommendationId:r.id,technicianId:c.tech.id}),/cannot approve/);const a=c.dispatch.assignAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,recommendationId:r.id,technicianId:c.tech.id});assert.equal(a.status,"assigned");});
test("reassignment requires reason and immutable assignment history is preserved",async()=>{const c=await setup(),w=item(c),r=c.dispatch.recommendAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id});c.dispatch.assignAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,recommendationId:r.id,technicianId:c.tech.id});assert.throws(()=>c.dispatch.reassignAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,recommendationId:r.id,technicianId:c.tech.id}),/reason/);c.dispatch.reassignAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,recommendationId:r.id,technicianId:c.tech.id,reason:"Coverage change"});assert.ok(c.dispatch.historyAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id}).length>=4);});
test("return to queue and dispatch lifecycle remain governed",async()=>{const c=await setup(),w=item(c),r=c.dispatch.recommendAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id});c.dispatch.assignAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,recommendationId:r.id,technicianId:c.tech.id});assert.equal(c.dispatch.returnToQueueAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,reason:"Customer reschedule"}).status,"unassigned");const r2=c.dispatch.recommendAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id});c.dispatch.assignAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,recommendationId:r2.id,technicianId:c.tech.id});assert.equal(c.dispatch.dispatchAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id}).status,"dispatched");});
test("dispatch exceptions are opened and resolved with audit integrity",async()=>{const c=await setup(),w=item(c),x=c.dispatch.addExceptionAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id,type:"customer-unavailable",detail:"No answer"});assert.equal(c.dispatch.resolveExceptionAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,exceptionId:x.id,resolution:"Customer reached"}).status,"resolved");assert.equal(c.auditLog.verify(),true);});
test("only the assigned technician receives a post-dispatch handoff",async()=>{const c=await setup(),w=item(c),r=c.dispatch.recommendAuthorized({sessionToken:c.sessions.dispatcher.token,tenantId:T,workItemId:w.id});c.dispatch.assignAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id,recommendationId:r.id,technicianId:c.tech.id});c.dispatch.dispatchAuthorized({sessionToken:c.sessions.manager.token,tenantId:T,workItemId:w.id});const h=c.dispatch.handoffAuthorized({sessionToken:c.sessions.tech.token,tenantId:T,workItemId:w.id});assert.equal(h.status,"ready-for-field-execution");assert.equal("jobExecution" in h,false);});
